# idk wtf is going here, so let's leave ts alone.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Oh my zsh
export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh
ZSH_THEME="robbyrussell"

# Plugins
plugins=(git)

# Syntax Highlighting and powerlevel10k
source $HOME/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Aliases
alias v="nvim"
alias install="sudo pacman -S"
alias update="sudo pacman -Syu"
alias fresh="clear ; history -c"
alias bye="shutdown -h now"
alias wink="reboot"
alias rem="sudo pacman -R"
alias pur="sudo pacman -Rns"
alias ff="fastfetch"
alias yt="ytfzf"
alias sv="sudo -E nvim"
alias never="history -p ; exit"
alias time="tty-clock"
alias ls="exa --icons"
alias t="exa --tree --icons"
alias play="yt -m"
alias sto="cd /run/user/1000/gvfs/ && ls"
alias pen="cd /run/media/ixubux/ && ls"
alias show="nsxiv"
alias h="history | fzf"
alias zzz="sudo systemctl suspend"

# Export related stuff
export PATH="$PATH:/home/ixubux/.local/bin"
export PATH=$PATH:/home/ixubux/.spicetify
